export default {
  backArrow: require('../assets/images/backArrow.png'),
  chatImage: require('../assets/images/chatimage.png'),
  eyeImage: require('../assets/images/eyeimage.png'),
  faceBook: require('../assets/images/facebook.png'),
  google: require('../assets/images/Google.png'),
  marketImage: require('../assets/images/marketimage.png'),
  messageImage: require('../assets/images/messageimage.png'),
  nibIamge: require('../assets/images/nibimage.png'),
  notification: require('../assets/images/notification.png'),
  plusimage: require('../assets/images/plusimage.png'),
  toDoList: require('../assets/images/todolist.png'),
  pushArrow: require('../assets/images/pushArrow.png'),
  Group141: require('../assets/images/Group 141.png'),
  Group142: require('../assets/images/Group 142.png'),
  Group143: require('../assets/images/Group 143.png'),
  circleImage: require('../assets/images/greycircle.png'),
  moreImage: require('../assets/images/moreimage.png'),
  pushArrowUp: require('../assets/images/pusharrowup.png'),
dotImage:require('../assets/images/dotImage.png'),
greyDot:require('../assets/images/greyDot.png'),
right:require('../assets/images/right.png'),
downArrow:require('../assets/images/downArrow.png'),
searchImage:require('../assets/images/imageSearch.png'),
duedate:require('../assets/images/dueDate.png'),
pdfImage:require('../assets/images/pdfimage.png'),
dots:require('../assets/images/dots.png'),
LogoM:require('../assets/images/logoM.png'),
Link:require('../assets/images/link.png'),
record:require('../assets/images/record.png'),
BlackHeart:require('../assets/images/blackHeart.png'),
GroupImage:require('../assets/images/groupImage.png'),
Play:require('../assets/images/Play.png'),
List:require('../assets/images/list.png'),
Bin:require('../assets/images/bin.png'),
Pen:require('../assets/images/pen.png'),
greyDots:require('../assets/images/greyDots.png'),
camera:require('../assets/images/camera.png'),
picUpload:require('../assets/images/picUpload.png'),
ArrowBack:require('../assets/images/arrowBack.png'),
BlackCircle:require('../assets/images/blackCircle.png'),
share:require('../assets/images/share.png'),
halfCircle:require('../assets/images/halfCircle.png'),
Working:require('../assets/images/working.png'),
teamWork:require('../assets/images/teamWork.png'),
teamImage:require('../assets/images/teamImage.png'),
arrowUp:require('../assets/images/arrowUp.png'),
documentPdf:require('../assets/images/documentPdf.png'),
mikeDean:require('../assets/images/MikeDean.png'),
verticalDots:require('../assets/images/verticaldots.png'),
recordBox:require('../assets/images/recordBox.png'),
Link1:require('../assets/images/LINK1.png'),
markCuban:require('../assets/images/markCuban.png'),
polygon:require('../assets/images/Polygon.png'),
Mark:require('../assets/images/Mark.png'),
warnings:require('../assets/images/warnings.png'),




};
