import {StyleSheet} from 'react-native';
import {colors, fonts} from '../../utils';

export default StyleSheet.create({
  pageView: {
    backgroundColor: colors.white,
    flex: 1,
  },
  plumberView: {
    height: 190,
    width: '85%',
    alignSelf: 'center',
    borderColor: colors.blue,
    backgroundColor: colors.blue,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 10,
  },
  scheduleText: {
    fontFamily: fonts.medium,
    fontSize: 14,
    color: colors.white,
    paddingVertical: 10,
  },
  schedule: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: colors.white,
  },
  nameView: {
    height: 90,
    flexDirection: 'row',
    width: '95%',
    alignSelf: 'center',
    borderColor: colors.white,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderRadius: 15,
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  jamesimage: {
    resizeMode: 'contain',
    height: 50,
    width: 50,
  },
  name: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: colors.black,
  },
  imageView: {
    resizeMode: 'contain',
    height: 20,
    width: 20,
    tintColor: colors.blue,
  },
  square: {
    height: 40,
    width: 40,
    borderColor: colors.lightBlue,
    backgroundColor: colors.lightBlue,
    borderWidth: 1,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  jamesrating: {
    flexDirection: 'column',
    paddingLeft: 10,
  },
  number: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.greyLight,
    paddingLeft: 5,
  },
  rate: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.black,
    paddingLeft: 5,
  },
  view: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  star: {
    resizeMode: 'contain',
    height: 15,
    width: 15,
  },
  trackView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    height: 80,
    width: '95%',
    marginTop: 10,
  },
  leavingText: {
    fontFamily: fonts.semiBold,
    fontSize: 14,
    color: colors.black,
    paddingLeft: 10,
  },
  detail: {
    fontFamily: fonts.light,
    fontSize: 12,
    color: colors.black,
    paddingLeft: 10,
    paddingVertical: 5,
  },
  leavingDate: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  map: {
    resizeMode: 'contain',
    height: 25,
    width: 25,
    tintColor: colors.white,
  },
  detailText: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  mapcircle: {
    height: 36,
    width: 36,
    borderColor: colors.blue,
    backgroundColor: colors.blue,
    borderWidth: 1,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
